### ISSUE TITLE
Concertar a confirmação de saída no terminal 

### ISSUE THREAD

**Issue by Doguinhoo** [Doguinhoo/controle#11]
Como resultado da separação da função libera, a confirmação de saída no terminal não faz nada.

Eu recomendo criar uma função separada verificar se o cpf é de uma pessoa válida (está no arquivo, ainda não saiu)

**Comment by eduardoAmroginski** [comment]
Opah, não entendi muito bem, seria uma função de busca do cpf para verificar se saiu ou ainda está presente? Poderia me passar mais detalhes?

**Comment by Doguinhoo** [comment]
Provavelmente não será mais necessário agora que temos uma GUI, mas queriam um jeito de cancelar o processo de cadastro sem fechar o programa no terminal.

**Comment by MarnieGrenat** [comment]
TUI será deprecado.
