### ISSUE TITLE
Resolver o caso em que o arquivo não existe na gui

### ISSUE THREAD

**Issue by patrulhasirius** [Doguinhoo/controle#20]
Por enquanto a gui não lida com o caso em que os arquivos de dados ainda não existem, é necessário fazer esse check e criar o arquivo do zero.

```
FileNotFoundError: [Errno 2] No such file or directory: './Abrigados/abrigados.csv'
```

**Comment by Doguinhoo** [comment]
Não acho que isso é um problema com a GUI, é na função de serializar um cadastro

**Comment by patrulhasirius** [comment]
Eu tinha resolvido este caso anteriormente quando a gente usava o terminal, imagino que no meio da conversão isso se perdeu.

**Comment by Doguinhoo** [comment]
Resolvido por aebf0961c16ec6bf8d208dae4287ab3568ec1029
