### ISSUE TITLE
Mudar estrutura de pastas

### ISSUE THREAD

**Issue by patrulhasirius** [Doguinhoo/controle#22]
Precisamos que as pastas de dados "Voluntarios" e "Abrigados" sejam movidas para dentro de uma pasta chamada "Dados-Enchente". Não esquecer de atualizar os caminhos que citam essas pastas.

**Comment by Doguinhoo** [comment]
Resolvido por e195f10b7d6e4534db4d3e6e0dba7ff9c848f3e6
