### ISSUE TITLE
Fazer MR para main e gerar versão 2.0.0

### ISSUE THREAD

**Issue by MarnieGrenat** [Doguinhoo/controle#26]

**Comment by Doguinhoo** [comment]
Eu não acho necessário criar um issue além da pull request

**Comment by MarnieGrenat** [comment]
É melhor controle demais do que controle de menos.
Assim todos os devs que estão contribuindo sabem que a partir dessa issue, estamos na v2.0.0.
Além disso, documenta as versões também (sabemos e documentamos que @MarnieGrenat que fez release da v2.0.0)
