### ISSUE TITLE
Adicionar checagem de cpf na janela de saída

### ISSUE THREAD

**Issue by Doguinhoo** [Doguinhoo/controle#29]
Atualmente, quando o cpf é enviado pela janela de saída, ela não avisa se é um cpf válido.

**Comment by eduardoAmroginski** [comment]
- Adicionada validação de cpf para de saida de voluntários e abrigados.

- Adicionado requirements.txt para todos os colaboradores seguirem com as mesmas versões de dependencias, assim evitando possiveis conflitos devido a versão das mesmas.

Pull Request: https://github.com/Doguinhoo/controle/pull/30

**Comment by Doguinhoo** [comment]
Resolvido por #36
