### ISSUE TITLE
Múltiplas saídas na gui

### ISSUE THREAD

**Issue by patrulhasirius** [Doguinhoo/controle#32]
Agora que estamos usando o mesmo arquivo por vários dias seria bom tirar o aviso que a pessoa já saiu caso ela tenha uma entrada mais recente.

Por exemplo, se alguém entrou dia 07 e saiu no mesmo dia, quando ela entrar no dia 08 e sair no mesmo dia não é necessário avisar que ela já saiu no dia 07, visto que é uma nova "estadia".

**Comment by Doguinhoo** [comment]
Eu não encontrei esse problema durante meus testes, pode descrever o que você fez?

**Comment by patrulhasirius** [comment]
Eu estou estava usando a branch da Gui, pode ser que esse seja o problema.

Tente cadastrar para uma pessoa só entrada, saída, entrada e mais uma saída para ver se o problema está resolvido na main
