### ISSUE TITLE
Remover a interface de terminal

### ISSUE THREAD

**Issue by Doguinhoo** [Doguinhoo/controle#41]
Agora que a GUI tem paridade completa, a TUI não é necessária.

**Comment by MarnieGrenat** [comment]
vou remover após liberar v3.0.0 (com o sistema de saúde)

**Comment by Doguinhoo** [comment]
As funções input_cpf e input_telefone ainda não foram removidas

**Comment by MarnieGrenat** [comment]
removemos TUI, mas vamos criar uma issue para remoção de codigo legado
