### ISSUE TITLE
Recuperar os dados de dias anteriores

### ISSUE THREAD

**Issue by Doguinhoo** [Doguinhoo/controle#9]
Para nos salvar trabalho poderíamos recuperar os dados de cada pessoa com base em cadastros anteriores.

Portanto seria melhor pedir o CPF primeiro, assim podemos checar uma tabela separada com os dados cadastrais mas que não seja vinculada a algum dia específico, caso o CPF seja localizado podemos completar os outros dados.

**Comment by PedroEsnaola** [comment]
Gabriela:
os dados do colegio mesquita estao sendo armazenados em um repositorio privado em @MarnieGrenat

**Comment by karasmaur** [comment]
Existem casos em que nao há CPF cadastrado(nao é obrigatorio). Nesse caso vale tentar verificar nome ou o numero de telefone também.

**Comment by Doguinhoo** [comment]
Testei aqui, parece que #15 funciona

**Comment by MarnieGrenat** [comment]
Eu testei anteriormente e não estava funcional. Vou fazer uma branch bugfix e subir.
